### ISSUE TITLE
Re-enable ability to see own body

### ISSUE THREAD

**Issue by Brian-McG** [Brian-McG/Tempest-Trace#38]

**Comment by Brian-McG** [comment]
I think some touch ups are required:
 - Looking as downwards as possible has some artefacts.
 - Climb needs a bit of a touch up, doesn't look natural.

**Comment by jacquesh** [comment]
Fixed the artifacts ( with b4da1f0) but regarding climb looking bad, what would you like to see?

**Comment by Brian-McG** [comment]
So the left hand seems to unnaturally come into view during a climb. A good example to see it is the orange wall near the stairs at building 2.

**Comment by Brian-McG** [comment]
Just another artefact, look straight down and climb a wall, you will see your own neck in view.

**Comment by jacquesh** [comment]
So to reiterate: what exactly do you expect to see? I realise that it looks a little strange but eh, thats what the animation does...it makes sense (to me at least) because I know what the animation is doing, so it doesn't look *that* strange, and there isn't very much I can do apart from moving/scaling the avatar and even that I can't do very much of without messing up other things (the setting its at currently was kept because its a reasonable balance of things looking cool/being able to see what your avatar is doing, and not having clipping and seeing the insides of things.

**Comment by Brian-McG** [comment]
I guess if you feel there is no issue with the hand, it is okay.
The issue with climbing and seeing your full neck is not okay.
